export enum Counties {
    Aberdeenshire = 'Aberdeenshire',
    Angus = 'Angus',
    Antrim = 'Antrim',
    Argyll = 'Argyll',
    Armagh = 'Armagh',
    Ayrshire = 'Ayrshire',
    Banffshire = 'Banffshire',
    Bedfordshire = 'Bedfordshire',
    Berkshire = 'Berkshire',
    Berwickshire = 'Berwickshire',
    Bristol = 'Bristol',
    Buckinghamshire = 'Buckinghamshire',
    Bute = 'Bute',
    Caithness = 'Caithness',
    Cambridgeshire = 'Cambridgeshire',
    Cheshire = 'Cheshire',
    CityofLondon = 'City of London',
    Clackmannanshire = 'Clackmannanshire',
    Clwyd = 'Clwyd',
    Cornwall = 'Cornwall',
    Cumbria = 'Cumbria',
    Derbyshire = 'Derbyshire',
    Devon = 'Devon',
    Dorset = 'Dorset',
    Down = 'Down',
    Dumfriesshire = 'Dumfriesshire',
    Dunbartonshire = 'Dunbartonshire',
    Durham = 'Durham',
    Dyfed = 'Dyfed',
    EastLothian = 'East Lothian',
    EastRidingofYorkshire = 'East Riding of Yorkshire',
    EastSussex = 'East Sussex',
    Essex = 'Essex',
    Fermanagh = 'Fermanagh',
    Fife = 'Fife',
    Gloucestershire = 'Gloucestershire',
    GreaterLondon = 'Greater London',
    GreaterManchester = 'Greater Manchester',
    Gwent = 'Gwent',
    Gwynedd = 'Gwynedd',
    Hampshire = 'Hampshire',
    Herefordshire = 'Herefordshire',
    Hertfordshire = 'Hertfordshire',
    Invernessshire = 'Inverness-shire',
    IsleofWight = 'Isle of Wight',
    Kent = 'Kent',
    Kincardineshire = 'Kincardineshire',
    Kinrossshire = 'Kinross-shire',
    Kirkcudbrightshire = 'Kirkcudbrightshire',
    Lanarkshire = 'Lanarkshire',
    Lancashire = 'Lancashire',
    Leicestershire = 'Leicestershire',
    Lincolnshire = 'Lincolnshire',
    Londonderry = 'Londonderry',
    Merseyside = 'Merseyside',
    MidGlamorgan = 'Mid Glamorgan',
    Midlothian = 'Midlothian',
    Moray = 'Moray',
    Nairnshire = 'Nairnshire',
    Norfolk = 'Norfolk',
    NorthYorkshire = 'North Yorkshire',
    Northamptonshire = 'Northamptonshire',
    Northumberland = 'Northumberland',
    Nottinghamshire = 'Nottinghamshire',
    Orkney = 'Orkney',
    Oxfordshire = 'Oxfordshire',
    Peeblesshire = 'Peeblesshire',
    Perthshire = 'Perthshire',
    Powys = 'Powys',
    Renfrewshire = 'Renfrewshire',
    RossandCromarty = 'Ross and Cromarty',
    Roxburghshire = 'Roxburghshire',
    Rutland = 'Rutland',
    Selkirkshire = 'Selkirkshire',
    Shetland = 'Shetland',
    Shropshire = 'Shropshire',
    Somerset = 'Somerset',
    SouthGlamorgan = 'South Glamorgan',
    SouthYorkshire = 'South Yorkshire',
    Staffordshire = 'Staffordshire',
    Stirlingshire = 'Stirlingshire',
    Suffolk = 'Suffolk',
    Surrey = 'Surrey',
    Sutherland = 'Sutherland',
    TyneandWear = 'Tyne and Wear',
    Tyrone = 'Tyrone',
    Warwickshire = 'Warwickshire',
    WestGlamorgan = 'West Glamorgan',
    WestLothian = 'West Lothian',
    WestMidlands = 'West Midlands',
    WestSussex = 'West Sussex',
    WestYorkshire = 'West Yorkshire',
    Wigtownshire = 'Wigtownshire',
    Wiltshire = 'Wiltshire',
    Worcestershire = 'Worcestershire',
}

export enum BillingAddressChoice {
    New,
    Existing,
}

export enum ShippingAddressChoice {
    New,
    Existing,
}
